{%set version = "1.0.5" %}

package:
  name: hachoir-regex
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/hachoir-regex/hachoir-regex-{{ version }}.tar.gz
  sha256: a35b2bb0ff11418230fffbb97605adba012bf65d2aba3e5e7d8295774d5ba986

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python <3
    - pip
  run:
    - python <3

test:
  imports:
    - hachoir_regex
    - hachoir_regex.parser
    - hachoir_regex.pattern
    - hachoir_regex.regex
    - hachoir_regex.tools
    - hachoir_regex.version

about:
  home: http://bitbucket.org/haypo/hachoir/wiki/hachoir-regex
  license: GPL 2.0
  license_file: COPYING
  license_family: GPL2
  summary: 'Manipulation of regular expressions (regex)'

extra:
  recipe-maintainers:
    - pmlandwehr
