# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "CYephd6vU8Xns61YUMkhkymNo1BXR/Qq+fG21jSPFlbx4O3UXnMcGLOlq88rUUke+a8sI/8HintRN4C/2JCM9R7OWj5f9gXpJG24lfCsNkLrnLo/4e1kl7qCXVUySURlaXCGfdOcLfi7dreXGBpLU0NORBpAG6IladinQgbMC7ZGyKtVrXs93NifIEn6STkqVjMc8jMXT/BCeQTFqeZBaVCXn50nppEE0b9Yoo6nC1logwREheK2wG3WRlLBYFKwTPJKUITgI4NUfMjDC8eqHEJMSSYLN6vmtGi+huiPG549TFoCYeJ1sI7V+tIJsEI3uZQ7+tZuqxof/PnRcVRKNA1L1Y/6m9lqNJnnAauC+/shF9u3H9jOtpWnDRq1vBtOuwceDaZu4anHixUSLnUbnWB1eLixnP1KTchG4W8ywtzvNDsLbBw3RhfN1dmijoKjIBTwucxOkOXGcypmyfsguK0GlrdUYlEx6xV+YWi3SHwhcTTJWo6Wu0VdbzuG3aim+x9QlQZRd2aG2JIO00ZmTNEuJ2KXlhF5Kf+hpKg8zRpeM53LW4WGQpcOKhcnqYGR7syg4JOyGo78qNy/jyW1PYw+AbmjUmqItMBldj7tJDvLZa1OZenGvcEHTmWTf9OTxnNEEJnrC0a/lIm6C3wh+xjGYNVV36pjm4W7AniWmiM="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
