# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "BazpPLIwVtjtdNKhXfEZ6Js+3qnot2csxsnlu2QDXjeyvhF3Tp1QlmskdZrBbWuAF9banqudVNgstC8EOG6jHHLTgmre416sD1RcpMmw0hFvkUkcSC5R58ucs3KxCI6zbFwRYBCrqAxZAbH/Q8sV92sdDabVR7q71peO7nw4XqdlVVJOVVPm48HZClalmrPuKCLpO6a37+fUBvSxokYkzQ47QroY4LwkcuE0Uvj1sGPBNFcHb9m2s8/7epR1qHL49S7AHlsmh8TTJf1VO8+VyeAdtlCm/XPkjQ54SmjadMgXHR1/lBAQMuPqrGSmVVtGQU6oAtZFPbQ9FHhKW9mhZ7VP89XI+8G5zXAhHVTMAQQqd1JIJzwoXXqfWsjc3aN11DETGkhoZhYjPFSouoUC2wHg3z8SVXhHEpupDZocnHXs3knf/QK9TKrcllhRh0rERlXnjs1bVp2y4jSCnGaBgwemdZOWBo6YBcNoUuGcbOUI8hyGxdWTDSMGnEmMgX7cjo4yiO9D7rH7vJMaj0o/RhtgjUbx1JtkngSLrOHCoUas+sVCyga3NECubsu5b2FkF1D2dnKcsCBsAUe0uzhLmkVO/N/iEPnGHYTUZGMK7Wpjq3NiAANa+xm6lESiIho+0gq7Fx6NxLbgPLYUZHDWCrEhN/syWYD+N2Z6NYWo928="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
