travis:
  secure:
    BINSTAR_TOKEN: CYephd6vU8Xns61YUMkhkymNo1BXR/Qq+fG21jSPFlbx4O3UXnMcGLOlq88rUUke+a8sI/8HintRN4C/2JCM9R7OWj5f9gXpJG24lfCsNkLrnLo/4e1kl7qCXVUySURlaXCGfdOcLfi7dreXGBpLU0NORBpAG6IladinQgbMC7ZGyKtVrXs93NifIEn6STkqVjMc8jMXT/BCeQTFqeZBaVCXn50nppEE0b9Yoo6nC1logwREheK2wG3WRlLBYFKwTPJKUITgI4NUfMjDC8eqHEJMSSYLN6vmtGi+huiPG549TFoCYeJ1sI7V+tIJsEI3uZQ7+tZuqxof/PnRcVRKNA1L1Y/6m9lqNJnnAauC+/shF9u3H9jOtpWnDRq1vBtOuwceDaZu4anHixUSLnUbnWB1eLixnP1KTchG4W8ywtzvNDsLbBw3RhfN1dmijoKjIBTwucxOkOXGcypmyfsguK0GlrdUYlEx6xV+YWi3SHwhcTTJWo6Wu0VdbzuG3aim+x9QlQZRd2aG2JIO00ZmTNEuJ2KXlhF5Kf+hpKg8zRpeM53LW4WGQpcOKhcnqYGR7syg4JOyGo78qNy/jyW1PYw+AbmjUmqItMBldj7tJDvLZa1OZenGvcEHTmWTf9OTxnNEEJnrC0a/lIm6C3wh+xjGYNVV36pjm4W7AniWmiM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
