travis:
  secure:
    BINSTAR_TOKEN: BazpPLIwVtjtdNKhXfEZ6Js+3qnot2csxsnlu2QDXjeyvhF3Tp1QlmskdZrBbWuAF9banqudVNgstC8EOG6jHHLTgmre416sD1RcpMmw0hFvkUkcSC5R58ucs3KxCI6zbFwRYBCrqAxZAbH/Q8sV92sdDabVR7q71peO7nw4XqdlVVJOVVPm48HZClalmrPuKCLpO6a37+fUBvSxokYkzQ47QroY4LwkcuE0Uvj1sGPBNFcHb9m2s8/7epR1qHL49S7AHlsmh8TTJf1VO8+VyeAdtlCm/XPkjQ54SmjadMgXHR1/lBAQMuPqrGSmVVtGQU6oAtZFPbQ9FHhKW9mhZ7VP89XI+8G5zXAhHVTMAQQqd1JIJzwoXXqfWsjc3aN11DETGkhoZhYjPFSouoUC2wHg3z8SVXhHEpupDZocnHXs3knf/QK9TKrcllhRh0rERlXnjs1bVp2y4jSCnGaBgwemdZOWBo6YBcNoUuGcbOUI8hyGxdWTDSMGnEmMgX7cjo4yiO9D7rH7vJMaj0o/RhtgjUbx1JtkngSLrOHCoUas+sVCyga3NECubsu5b2FkF1D2dnKcsCBsAUe0uzhLmkVO/N/iEPnGHYTUZGMK7Wpjq3NiAANa+xm6lESiIho+0gq7Fx6NxLbgPLYUZHDWCrEhN/syWYD+N2Z6NYWo928=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
